In [1]:
from sklearn.naive_bayes import CategoricalNB
clf=CategoricalNB()

In [2]:
import pandas as pd
NB1=pd.read_csv("Downloads\\SalaryData_Test.csv")
NB1

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

In [3]:
NB2=pd.read_csv("Downloads\\SalaryData_Train.csv")
NB2

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [4]:
NB1new = NB1.drop(NB1.columns[[0,3,9,10,11]], axis=1)
NB1new

workclass      education        maritalstatus          occupation  \
0            Private           11th        Never-married   Machine-op-inspct   
1            Private        HS-grad   Married-civ-spouse     Farming-fishing   
2          Local-gov     Assoc-acdm   Married-civ-spouse     Protective-serv   
3            Private   Some-college   Married-civ-spouse   Machine-op-inspct   
4            Private           10th        Never-married       Other-service   
...              ...            ...                  ...                 ...   
15055        Private      Bachelors        Never-married      Prof-specialty   
15056        Private      Bachelors             Divorced      Prof-specialty   
15057        Private      Bachelors   Married-civ-spouse      Prof-specialty   
15058        Private      Bachelors             Divorced        Adm-clerical   
15059   Self-emp-inc      Bachelors   Married-civ-spouse     Exec-managerial   

         relationship                 race      sex          native  Salary  
0           Own-child                Black     Male   United-States   <=50K  
1             Husband                White     Male   United-States   <=50K  
2             Husband                White     Male   United-States    >50K  
3             Husband                Black     Male   United-States    >50K  
4       Not-in-family                White     Male   United-States   <=50K  
...               ...                  ...      ...             ...     ...  
15055       Own-child                White     Male   United-States   <=50K  
15056   Not-in-family                White   Female   United-States   <=50K  
15057         Husband                White     Male   United-States   <=50K  
15058       Own-child   Asian-Pac-Islander     Male   United-States   <=50K  
15059         Husband                White     Male   United-States    >50K  

[15060 rows x 9 columns]

In [5]:
NB2new=df = NB2.drop(NB2.columns[[0,3,9,10,11]], axis=1)
NB2new

workclass    education        maritalstatus  \
0              State-gov    Bachelors        Never-married   
1       Self-emp-not-inc    Bachelors   Married-civ-spouse   
2                Private      HS-grad             Divorced   
3                Private         11th   Married-civ-spouse   
4                Private    Bachelors   Married-civ-spouse   
...                  ...          ...                  ...   
30156            Private   Assoc-acdm   Married-civ-spouse   
30157            Private      HS-grad   Married-civ-spouse   
30158            Private      HS-grad              Widowed   
30159            Private      HS-grad        Never-married   
30160       Self-emp-inc      HS-grad   Married-civ-spouse   

               occupation    relationship    race      sex          native  \
0            Adm-clerical   Not-in-family   White     Male   United-States   
1         Exec-managerial         Husband   White     Male   United-States   
2       Handlers-cleaners   Not-in-family   White     Male   United-States   
3       Handlers-cleaners         Husband   Black     Male   United-States   
4          Prof-specialty            Wife   Black   Female            Cuba   
...                   ...             ...     ...      ...             ...   
30156        Tech-support            Wife   White   Female   United-States   
30157   Machine-op-inspct         Husband   White     Male   United-States   
30158        Adm-clerical       Unmarried   White   Female   United-States   
30159        Adm-clerical       Own-child   White     Male   United-States   
30160     Exec-managerial            Wife   White   Female   United-States   

       Salary  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
30156   <=50K  
30157    >50K  
30158   <=50K  
30159   <=50K  
30160    >50K  

[30161 rows x 9 columns]

In [6]:
NB1new_label=NB1new.copy()

In [7]:
NB2new_label=NB2new.copy()

In [8]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
NB1new_label.iloc[:,-1]=labelencoder.fit_transform(NB1new_label.iloc[:,-1])
NB1new_label.iloc[:,0]=labelencoder.fit_transform(NB1new_label.iloc[:,0])
NB1new_label.iloc[:,1]=labelencoder.fit_transform(NB1new_label.iloc[:,1])
NB1new_label.iloc[:,2]=labelencoder.fit_transform(NB1new_label.iloc[:,2])
NB1new_label.iloc[:,3]=labelencoder.fit_transform(NB1new_label.iloc[:,3])
NB1new_label.iloc[:,4]=labelencoder.fit_transform(NB1new_label.iloc[:,4])
NB1new_label.iloc[:,5]=labelencoder.fit_transform(NB1new_label.iloc[:,5])
NB1new_label.iloc[:,6]=labelencoder.fit_transform(NB1new_label.iloc[:,6])
NB1new_label.iloc[:,7]=labelencoder.fit_transform(NB1new_label.iloc[:,7])

In [9]:
NB1new_label

workclass  education  maritalstatus  occupation  relationship  race  \
0              2          1              4           6             3     2   
1              2         11              2           4             0     4   
2              1          7              2          10             0     4   
3              2         15              2           6             0     2   
4              2          0              4           7             1     4   
...          ...        ...            ...         ...           ...   ...   
15055          2          9              4           9             3     4   
15056          2          9              0           9             1     4   
15057          2          9              2           9             0     4   
15058          2          9              0           0             3     1   
15059          3          9              2           3             0     4   

       sex  native  Salary  
0        1      37       0  
1        1      37       0  
2        1      37       1  
3        1      37       1  
4        1      37       0  
...    ...     ...     ...  
15055    1      37       0  
15056    0      37       0  
15057    1      37       0  
15058    1      37       0  
15059    1      37       1  

[15060 rows x 9 columns]

In [10]:
NB2new_label.iloc[:,-1]=labelencoder.fit_transform(NB2new_label.iloc[:,-1])
NB2new_label.iloc[:,0]=labelencoder.fit_transform(NB2new_label.iloc[:,0])
NB2new_label.iloc[:,1]=labelencoder.fit_transform(NB2new_label.iloc[:,1])
NB2new_label.iloc[:,2]=labelencoder.fit_transform(NB2new_label.iloc[:,2])
NB2new_label.iloc[:,3]=labelencoder.fit_transform(NB2new_label.iloc[:,3])
NB2new_label.iloc[:,4]=labelencoder.fit_transform(NB2new_label.iloc[:,4])
NB2new_label.iloc[:,5]=labelencoder.fit_transform(NB2new_label.iloc[:,5])
NB2new_label.iloc[:,6]=labelencoder.fit_transform(NB2new_label.iloc[:,6])
NB2new_label.iloc[:,7]=labelencoder.fit_transform(NB2new_label.iloc[:,7])

In [11]:
NB2new_label

workclass  education  maritalstatus  occupation  relationship  race  \
0              5          9              4           0             1     4   
1              4          9              2           3             0     4   
2              2         11              0           5             1     4   
3              2          1              2           5             0     2   
4              2          9              2           9             5     2   
...          ...        ...            ...         ...           ...   ...   
30156          2          7              2          12             5     4   
30157          2         11              2           6             0     4   
30158          2         11              6           0             4     4   
30159          2         11              4           0             3     4   
30160          3         11              2           3             5     4   

       sex  native  Salary  
0        1      37       0  
1        1      37       0  
2        1      37       0  
3        1      37       0  
4        0       4       0  
...    ...     ...     ...  
30156    0      37       0  
30157    1      37       1  
30158    0      37       0  
30159    1      37       0  
30160    0      37       1  

[30161 rows x 9 columns]

In [12]:
x1=NB1new_label.iloc[:,:-1]
y1=NB1new_label.iloc[:,-1]

In [13]:
x2=NB2new_label.iloc[:,:-1]
y2=NB2new_label.iloc[:,-1]

In [14]:
clf.fit(x1,y1)

CategoricalNB()

In [15]:
clf.fit(x2,y2)

CategoricalNB()

In [26]:
import numpy as np

In [39]:
#<=50K:0,>50K:1;
#Private=2,11th=1,Never-married=4,Machine-op-inspct=6,Own-child=3,Black=2,Male=1,United-States=37;
x1_test=np.array([[2,1,4,6,3,2,1,37]])

In [28]:
print(clf.predict(x1_test))

[0]


In [29]:
clf.predict_proba(x1_test)

array([[9.99903937e-01, 9.60627381e-05]])

In [40]:
#Local-gov=1,Assoc-acdm=7,Married-civ-spouse=2,Protective-serv=10,Husband=0,White=4,Male=1,United-States=37;
x1_test=np.array([[1,7,2,10,0,4,1,37]])

In [41]:
print(clf.predict(x1_test))

[1]


In [42]:
clf.predict_proba(x1_test)

array([[0.14083036, 0.85916964]])

In [43]:
#State-gov=5,Bachelors=9,Never-married=4,Adm-clerical=0,Not-in-family=1,White=4,Male=1,United-States=37;
x2_test=np.array([[5,9,4,0,1,4,1,37]])

In [44]:
print(clf.predict(x2_test))

[0]


In [45]:
clf.predict_proba(x2_test)

array([[0.96913859, 0.03086141]])

In [46]:
#Self-emp-inc=3,HS-grad=11,Married-civ-spouse=2,Exec-managerial=3,Wife=5,White=4,Female=0,United-States=37;
x2_test=np.array([[3,11,2,3,5,4,0,37]])

In [47]:
print(clf.predict(x2_test))

[1]


In [48]:
clf.predict_proba(x2_test)

array([[0.12889287, 0.87110713]])